Repository Mintplex-Labs/anything-llm, pull requests merged in 2024-06, with the labels that each got.

#1579 [FEAT] Add LiteLLM embedding provider support
  docker/.env.example
  frontend/src/components/EmbeddingSelection/LiteLLMOptions/index.jsx
  frontend/src/pages/GeneralSettings/EmbeddingPreference/index.jsx
  frontend/src/pages/OnboardingFlow/Steps/DataHandling/index.jsx
  server/.env.example
  server/utils/EmbeddingEngines/liteLLM/index.js
  server/utils/helpers/index.js
  server/utils/helpers/updateENV.js
Labels: needs review

#1392 [FEAT] Edit message button
  frontend/package.json
  frontend/src/components/ChatBubble/index.jsx
  frontend/src/components/DefaultChat/index.jsx
  frontend/src/components/UserIcon/index.jsx
  frontend/src/components/UserIcon/workspace.png
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/Actions/EditMessage/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/Actions/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/PromptReply/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/index.jsx
  frontend/src/components/WorkspaceChat/index.jsx
  frontend/src/models/workspace.js
  frontend/src/models/workspaceThread.js
  frontend/src/utils/chat/index.js
  server/endpoints/workspaceThreads.js
  server/endpoints/workspaces.js
  server/models/workspaceChats.js
  server/utils/helpers/chat/responses.js
Labels: needs review

#1602 [FIX] Login screen image ui bug fix + fix footer icons when overflowing
  frontend/src/components/Modals/Password/index.jsx
  frontend/src/components/SettingsSidebar/index.jsx
  frontend/src/components/Sidebar/index.jsx
Labels: needs review

#1561 [FIX] Incorrect vectors count with Qdrant
  server/package.json
  server/utils/vectorDbProviders/qdrant/index.js
  server/yarn.lock
Labels: needs review

#1607 [FEAT] Rename new threads on thread creation
  frontend/src/components/Sidebar/ActiveWorkspaces/ThreadContainer/ThreadItem/index.jsx
  frontend/src/components/Sidebar/ActiveWorkspaces/ThreadContainer/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/index.jsx
  server/endpoints/chat.js
  server/models/workspaceThread.js
  server/package.json
  server/yarn.lock
Labels: needs review

#1665 [STYLE] Agent UI mobile styles
  frontend/src/components/ContextualSaveBar/index.jsx
  frontend/src/pages/Admin/Agents/SQLConnectorSelection/NewConnectionModal.jsx
  frontend/src/pages/Admin/Agents/index.jsx
Labels: needs review

#1700 [STYLE] Document picker UI improvements
  frontend/src/components/Modals/ManageWorkspace/Documents/Directory/FileRow/index.jsx
  frontend/src/components/Modals/ManageWorkspace/Documents/Directory/index.jsx
  frontend/src/components/Modals/ManageWorkspace/Documents/WorkspaceDirectory/WorkspaceFileRow/index.jsx
  frontend/src/components/Modals/ManageWorkspace/Documents/WorkspaceDirectory/index.jsx
Labels: needs review

#1716 Add watch support to YouTube transcripts
  collector/extensions/index.js
  collector/extensions/resync/index.js
  collector/utils/extensions/Confluence/index.js
  collector/utils/extensions/YoutubeTranscript/index.js
  server/jobs/sync-watched-documents.js
  server/models/documentSyncQueue.js
  server/models/documentSyncRun.js
  server/models/documents.js
Labels: blocked

#1709 update: complete login page Mandarin translation.
  frontend/src/components/Modals/Password/MultiUserAuth.jsx
  frontend/src/locales/zh/common.js
Labels: needs review

#1727 [FEAT] Persist query mode refusal responses as chat history
  server/models/workspaceChats.js
  server/utils/chats/index.js
  server/utils/chats/stream.js
Labels: needs review

#1668 [FEAT] Workspace threads developer API endpoints
  server/endpoints/api/index.js
  server/endpoints/api/workspaceThread/index.js
  server/swagger/init.js
  server/swagger/openapi.json
Labels: blocked, needs review

#1743 fix: sanitize filename before writing
  collector/utils/extensions/Confluence/index.js
  collector/utils/files/index.js
Labels: needs review

#1756 [FEAT] Auto detection for Ollama and LMStudio
  frontend/src/components/EmbeddingSelection/LMStudioOptions/index.jsx
  frontend/src/components/EmbeddingSelection/OllamaOptions/index.jsx
  frontend/src/components/LLMSelection/LMStudioOptions/index.jsx
  frontend/src/components/LLMSelection/OllamaLLMOptions/index.jsx
  frontend/src/hooks/useProviderEndpointAutoDiscovery.js
  frontend/src/models/system.js
  frontend/src/utils/constants.js
Labels: needs review

#1742 [FEAT] Remove users_can_delete_workspaces feature
  frontend/src/locales/en/common.js
  frontend/src/locales/es/common.js
  frontend/src/locales/fr/common.js
  frontend/src/locales/ru/common.js
  frontend/src/locales/zh/common.js
  frontend/src/models/system.js
  frontend/src/pages/Admin/System/index.jsx
  frontend/src/pages/WorkspaceSettings/GeneralAppearance/DeleteWorkspace/index.jsx
  server/endpoints/admin.js
  server/endpoints/api/admin/index.js
  server/endpoints/system.js
  server/models/systemSettings.js
  server/prisma/seed.js
  server/swagger/openapi.json
Labels: needs review
