Repository Mintplex-Labs/anything-llm, pull requests merged in 2025-07, with the labels that each got.

#4079 Add option to disable streaming via env for generic openai provider
  server/utils/AiProviders/genericOpenAi/index.js
Labels: blocked

#4084 LMStudio 0 value embeddings patch
  server/utils/EmbeddingEngines/lmstudio/index.js
Labels: PR:needs review

#4076 Add hint for chats in query mode
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatTooltips/index.jsx
  frontend/src/locales/ar/common.js
  frontend/src/locales/da/common.js
  frontend/src/locales/de/common.js
  frontend/src/locales/en/common.js
  frontend/src/locales/es/common.js
  frontend/src/locales/et/common.js
  frontend/src/locales/fa/common.js
  frontend/src/locales/fr/common.js
  frontend/src/locales/he/common.js
  frontend/src/locales/it/common.js
  frontend/src/locales/ja/common.js
  frontend/src/locales/ko/common.js
  frontend/src/locales/lv/common.js
  frontend/src/locales/nl/common.js
  frontend/src/locales/pt_BR/common.js
  frontend/src/locales/ru/common.js
  frontend/src/locales/tr/common.js
  frontend/src/locales/vn/common.js
  frontend/src/locales/zh/common.js
  frontend/src/locales/zh_TW/common.js
  frontend/src/utils/paths.js
Labels: PR:needs review

#4134 Add option to enable encryption on MSSQL Server db
  frontend/src/pages/Admin/Agents/SQLConnectorSelection/NewConnectionModal.jsx
  server/__tests__/utils/SQLConnectors/connectionParser.test.js
  server/utils/agents/aibitat/plugins/sql-agent/SQLConnectors/MSSQL.js
Labels: PR:needs review

#4178 Moonshot AI LLM & agent provider
  README.md
  docker/.env.example
  frontend/src/components/LLMSelection/MoonshotAiOptions/index.jsx
  frontend/src/media/llmprovider/moonshotai.png
  frontend/src/pages/GeneralSettings/LLMPreference/index.jsx
  frontend/src/pages/OnboardingFlow/Steps/DataHandling/index.jsx
  frontend/src/pages/OnboardingFlow/Steps/LLMPreference/index.jsx
  frontend/src/pages/WorkspaceSettings/AgentConfig/AgentLLMSelection/index.jsx
  server/.env.example
  server/endpoints/utils.js
  server/models/systemSettings.js
  server/utils/AiProviders/modelMap/index.js
  server/utils/AiProviders/moonshotAi/index.js
  server/utils/agents/aibitat/index.js
  server/utils/agents/aibitat/providers/ai-provider.js
  server/utils/agents/aibitat/providers/index.js
  server/utils/agents/aibitat/providers/moonshotAi.js
  server/utils/agents/index.js
  server/utils/helpers/customModels.js
  server/utils/helpers/index.js
  server/utils/helpers/updateENV.js
Labels: Integration Request, PR:needs review

#4216 STT append spoken text
  frontend/src/components/WorkspaceChat/ChatContainer/PromptInput/SpeechToText/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/PromptInput/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/index.jsx
Labels: PR:needs review
