Repository Mintplex-Labs/anything-llm, pull requests merged in 2025-05, with the labels that each got.

#3714 Refactor AWS Bedrock Provider for Multi-modal Support & Correct Token Limits
  docker/.env.example
  frontend/src/components/LLMSelection/AwsBedrockLLMOptions/index.jsx
  server/.env.example
  server/models/systemSettings.js
  server/utils/AiProviders/bedrock/index.js
  server/utils/AiProviders/bedrock/utils.js
  server/utils/helpers/updateENV.js
Labels: PR:needs review

#3271 feat: support fetch wikis for gitlab data connectors
  collector/utils/extensions/RepoLoader/GitlabRepo/RepoLoader/index.js
  collector/utils/extensions/RepoLoader/GitlabRepo/index.js
  frontend/src/components/Modals/ManageWorkspace/DataConnectors/Connectors/Gitlab/index.jsx
  frontend/src/models/dataConnector.js
Labels: PR:needs review

#3770 Chat prompt history menu
  frontend/src/locales/ar/common.js
  frontend/src/locales/da/common.js
  frontend/src/locales/de/common.js
  frontend/src/locales/en/common.js
  frontend/src/locales/es/common.js
  frontend/src/locales/fa/common.js
  frontend/src/locales/fr/common.js
  frontend/src/locales/he/common.js
  frontend/src/locales/it/common.js
  frontend/src/locales/ja/common.js
  frontend/src/locales/ko/common.js
  frontend/src/locales/nl/common.js
  frontend/src/locales/pt_BR/common.js
  frontend/src/locales/ru/common.js
  frontend/src/locales/tr/common.js
  frontend/src/locales/vn/common.js
  frontend/src/locales/zh/common.js
  frontend/src/locales/zh_TW/common.js
  frontend/src/models/promptHistory.js
  frontend/src/pages/WorkspaceSettings/ChatSettings/ChatPromptSettings/ChatPromptHistory/PromptHistoryItem/index.jsx
  frontend/src/pages/WorkspaceSettings/ChatSettings/ChatPromptSettings/ChatPromptHistory/index.jsx
  frontend/src/pages/WorkspaceSettings/ChatSettings/ChatPromptSettings/index.jsx
  server/endpoints/workspaces.js
  server/models/promptHistory.js
  server/models/workspace.js
  server/prisma/migrations/20250506214129_init/migration.sql
  server/prisma/schema.prisma
Labels: PR:Ready-to-merge

#3792 Update:WorkspaceChat-ChatContainer-PromptInput
  frontend/src/components/WorkspaceChat/ChatContainer/PromptInput/index.jsx
Labels: PR:needs review

#3817 Automatic Context window detection
  server/storage/models/.gitignore
  server/utils/AiProviders/anthropic/index.js
  server/utils/AiProviders/cohere/index.js
  server/utils/AiProviders/deepseek/index.js
  server/utils/AiProviders/gemini/defaultModels.js
  server/utils/AiProviders/gemini/index.js
  server/utils/AiProviders/gemini/syncStaticLists.mjs
  server/utils/AiProviders/groq/index.js
  server/utils/AiProviders/modelMap/index.js
  server/utils/AiProviders/modelMap/legacy.js
  server/utils/AiProviders/openAi/index.js
  server/utils/AiProviders/xai/index.js
Labels: PR:Ready-to-merge

#3833 3416 file picker load times
  server/utils/files/index.js
Labels: PR:needs review

#3832 Disable message send while content is embedding
  frontend/src/components/WorkspaceChat/ChatContainer/DnDWrapper/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/PromptInput/index.jsx
  frontend/src/locales/ar/common.js
  frontend/src/locales/da/common.js
  frontend/src/locales/de/common.js
  frontend/src/locales/en/common.js
  frontend/src/locales/es/common.js
  frontend/src/locales/fa/common.js
  frontend/src/locales/fr/common.js
  frontend/src/locales/he/common.js
  frontend/src/locales/it/common.js
  frontend/src/locales/ja/common.js
  frontend/src/locales/ko/common.js
  frontend/src/locales/nl/common.js
  frontend/src/locales/pt_BR/common.js
  frontend/src/locales/ru/common.js
  frontend/src/locales/tr/common.js
  frontend/src/locales/vn/common.js
  frontend/src/locales/zh/common.js
  frontend/src/locales/zh_TW/common.js
Labels: UI/UX, PR:needs review

#3865 Removed redundant scrollbar in search containers
  frontend/src/pages/Admin/Agents/WebSearchSelection/index.jsx
  frontend/src/pages/GeneralSettings/AudioPreference/stt.jsx
  frontend/src/pages/GeneralSettings/AudioPreference/tts.jsx
  frontend/src/pages/GeneralSettings/EmbeddingPreference/index.jsx
  frontend/src/pages/GeneralSettings/LLMPreference/index.jsx
  frontend/src/pages/GeneralSettings/TranscriptionPreference/index.jsx
  frontend/src/pages/GeneralSettings/VectorDatabase/index.jsx
  frontend/src/pages/WorkspaceSettings/AgentConfig/AgentLLMSelection/index.jsx
  frontend/src/pages/WorkspaceSettings/ChatSettings/WorkspaceLLMSelection/index.jsx
Labels: blocked, needs info / can't replicate

#3837 Update citations UI
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/Citation/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatTooltips/index.jsx
  frontend/src/index.css
Labels: blocked
