Repository Mintplex-Labs/anything-llm, pull requests merged in 2025-02, with the labels that each got.

#3110 fix UserMenu rendered twice on Main page
  frontend/src/pages/Main/index.jsx
Labels: needs review

#3206 feat(dataconnectors): support confluence personal access token
  collector/utils/extensions/Confluence/index.js
  frontend/src/components/Modals/ManageWorkspace/DataConnectors/Connectors/Confluence/index.jsx
  frontend/src/models/dataConnector.js
Labels: needs review

#3247 for projects in gitlab subgroup (#3075)
  collector/utils/extensions/RepoLoader/GitlabRepo/RepoLoader/index.js
Labels: needs review

#3246 fix: sanitizeNamespace
  server/utils/vectorDbProviders/astra/index.js
Labels: needs review

#3258 feat: Add endpoint to retrieve documents by folder name
  server/endpoints/api/document/index.js
  server/swagger/openapi.json
  server/utils/files/index.js
Labels: needs review

#3005 2749 ollama client auth token
  docker/.env.example
  frontend/src/components/LLMSelection/OllamaLLMOptions/index.jsx
  frontend/src/hooks/useProviderEndpointAutoDiscovery.js
  server/.env.example
  server/models/systemSettings.js
  server/package.json
  server/storage/models/.gitignore
  server/utils/AiProviders/ollama/index.js
  server/utils/agents/aibitat/providers/ollama.js
  server/utils/helpers/customModels.js
  server/utils/helpers/updateENV.js
  server/yarn.lock
Labels: needs review

#3267 Markdown support in custom messages
  frontend/src/components/ChatBubble/index.jsx
  frontend/src/components/EditingChatBubble/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx
  frontend/src/utils/chat/purify.js
Labels: needs review

#3244 feature: support configurable left and right message layout
  frontend/src/components/DefaultChat/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/Actions/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/index.jsx
  frontend/src/hooks/useChatMessageAlignment.js
  frontend/src/pages/GeneralSettings/Appearance/MessageDirection/index.jsx
  frontend/src/pages/GeneralSettings/Appearance/index.jsx
Labels: needs review

#3276 feat: Add endpoint to upload documents to a specified folder
  server/endpoints/api/document/index.js
  server/swagger/openapi.json
Labels: needs review

#3330 speech to text typo correction
  .gitignore
  frontend/src/components/WorkspaceChat/ChatContainer/PromptInput/SpeechToText/index.jsx
  frontend/src/components/WorkspaceChat/ChatContainer/index.jsx
Labels: needs review

#3354 Windows development environment variables support
  collector/package.json
  collector/yarn.lock
  frontend/package.json
  frontend/yarn.lock
  server/package.json
  server/yarn.lock
Labels: needs review

#3211 Add new model provider PPIO
  .vscode/settings.json
  README.md
  docker/.env.example
  frontend/src/components/LLMSelection/PPIOLLMOptions/index.jsx
  frontend/src/hooks/useGetProvidersModels.js
  frontend/src/media/llmprovider/ppio.png
  frontend/src/pages/GeneralSettings/LLMPreference/index.jsx
  frontend/src/pages/OnboardingFlow/Steps/DataHandling/index.jsx
  frontend/src/pages/OnboardingFlow/Steps/LLMPreference/index.jsx
  frontend/src/pages/WorkspaceSettings/AgentConfig/AgentLLMSelection/index.jsx
  locales/README.fa-IR.md
  locales/README.ja-JP.md
  locales/README.tr-TR.md
  locales/README.zh-CN.md
  server/.env.example
  server/models/systemSettings.js
  server/storage/models/.gitignore
  server/utils/AiProviders/ppio/index.js
  server/utils/agents/aibitat/index.js
  server/utils/agents/aibitat/providers/ai-provider.js
  server/utils/agents/aibitat/providers/index.js
  server/utils/agents/aibitat/providers/ppio.js
  server/utils/agents/index.js
  server/utils/helpers/customModels.js
  server/utils/helpers/index.js
  server/utils/helpers/updateENV.js
Labels: blocked

#3325 feat: Add multilingual support for ocr module
  collector/processSingleFile/convert/asImage.js
  collector/processSingleFile/convert/asPDF/index.js
  collector/utils/OCRLoader/index.js
  collector/utils/OCRLoader/validLangs.js
  docker/.env.example
  server/.env.example
  server/utils/collectorApi/index.js
  server/utils/helpers/updateENV.js
Labels: blocked, needs review
